# Site settings
<<<<<<< HEAD
<<<<<<< HEAD
title: Horta da Cooperativa
description: >-
  Manual de Sobrevivência Para Labregos Humanos
baseurl: ""
url: "https://horta-da-cooperativa.github.io"
github_username:  horta-da-cooperativa
=======
=======
>>>>>>> dev
url: "https://horta-da-cooperativa.github.io/"
title: Horta da Cooperativa
description: Manual de Sobrevivência Para Labregos Urbanos
lang: pt_PT

# Contact settings
email: congolito@riseup.net
github: horta-da-cooperativa

# Jekyll settings
permalink: /:year/:month/:day/:title/

paginate: 6
paginate_path: /page:num/

collections:
  calendario:
    output: true
  culturas:
    output: true

highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
<<<<<<< HEAD
>>>>>>> dev
=======
>>>>>>> dev

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

sass:
    style: compressed

include: [_pages]
exclude: [README.md, LICENSE.md, Gemfile, Gemfile.lock]
